package io.github.juliog516.JMockaroo.Helpers;

public enum DataTypes {
    AddressLine2("Address Line 2"),
    AirportCode("Airport Code"),
    AirportContinent("Airport Continent"),
    AirportCountryCode("Airport Country Code"),
    AirportElevationFeet("Airport Elevation (Feet)"),
    AirportGpsCode("Airport GPS Code"),
    AirportLatitude("Airport Latitude"),
    AirportLongitude("Airport Longitude"),
    AirportMunicipality("Airport Municipality"),
    AirportName("Airport Name"),
    AirportRegionCode("Airport Region Code"),
    AnimalCommonName("Animal Common Name"),
    AnimalScientificName("Animal Scientific Name"),
    AppBundleId("App Bundle ID"),
    AppName("App Name"),
    AppVersion("App Version"),
    Avatar("Avatar"),
    Base64ImageUrl("Base64 Image URL"),
    BinomialDistribution("Binomial Distribution"),
    BitcoinAddress("Bitcoin Address"),
    Blank("Blank"),
    Boolean("Boolean"),
    Buzzword("Buzzword"),
    CarMake("Car Make"),
    CarModel("Car Model"),
    CarModelYear("Car Model Year"),
    CarVin("Car VIN"),
    CatchPhrase("Catch Phrase"),
    CharacterSequence("Character Sequence"),
    City("City"),
    Color("Color"),
    CompanyName("Company Name"),
    ConstructionHeavyEquipment("Construction Heavy Equipment"),
    ConstructionMaterial("Construction Material"),
    ConstructionRole("Construction Role"),
    ConstructionStandardCostCode("Construction Standard Cost Code"),
    ConstructionSubcontractCategory("Construction Subcontract Category"),
    ConstructionTrade("Construction Trade"),
    Country("Country"),
    CountryCode("Country Code"),
    CreditCardHashTag("Credit Card #"),
    CreditCardType("Credit Card Type"),
    Currency("Currency"),
    CurrencyCode("Currency Code"),
    CustomList("Custom List"),
    DatasetColumn("Dataset Column"),
    Datetime("Datetime"),
    DepartmentCorporate("Department (Corporate)"),
    DepartmentRetail("Department (Retail)"),
    DigitSequence("Digit Sequence"),
    DomainName("Domain Name"),
    DrugCompany("Drug Company"),
    DrugNameBrand("Drug Name (Brand)"),
    DrugNameGeneric("Drug Name (Generic)"),
    DummyImageUrl("Dummy Image URL"),
    DunsNumber("DUNS Number"),
    Ein("EIN"),
    EmailAddress("Email Address"),
    Encrypt("Encrypt"),
    EthereumAddress("Ethereum Address"),
    ExponentialDistribution("Exponential Distribution"),
    FakeCompanyName("Fake Company Name"),
    FamilyNameChinese("Family Name (Chinese)"),
    FdaNdcCode("FDA NDC Code"),
    FileName("File Name"),
    FirstName("First Name"),
    FirstNameEuropean("First Name (European)"),
    FirstNameFemale("First Name (Female)"),
    FirstNameMale("First Name (Male)"),
    Formula("Formula"),
    Frequency("Frequency"),
    FullName("Full Name"),
    Gender("Gender"),
    GenderAbbrev("Gender (abbrev)"),
    GenderBinary("Gender (Binary)"),
    GenderFacebook("Gender (Facebook)"),
    GeometricDistribution("Geometric Distribution"),
    GivenNameChinese("Given Name (Chinese)"),
    Guid("GUID"),
    HexColor("Hex Color"),
    Iban("IBAN"),
    Icd10DiagnosisCode("ICD10 Diagnosis Code"),
    Icd10DxDescLong("ICD10 Dx Desc (Long)"),
    Icd10DxDescShort("ICD10 Dx Desc (Short)"),
    Icd10ProcDescLong("ICD10 Proc Desc (Long)"),
    Icd10ProcDescShort("ICD10 Proc Desc (Short)"),
    Icd10ProcedureCode("ICD10 Procedure Code"),
    Icd9DiagnosisCode("ICD9 Diagnosis Code"),
    Icd9DxDescLong("ICD9 Dx Desc (Long)"),
    Icd9DxDescShort("ICD9 Dx Desc (Short)"),
    Icd9ProcDescLong("ICD9 Proc Desc (Long)"),
    Icd9ProcDescShort("ICD9 Proc Desc (Short)"),
    Icd9ProcedureCode("ICD9 Procedure Code"),
    IpAddressV4("IP Address v4"),
    IpAddressV4Cidr("IP Address v4 CIDR"),
    IpAddressV6("IP Address v6"),
    IpAddressV6Cidr("IP Address v6 CIDR"),
    Isbn("ISBN"),
    JobTitle("Job Title"),
    JsonArray("JSON Array"),
    Language("Language"),
    LastName("Last Name"),
    Latitude("Latitude"),
    LinkedinSkill("LinkedIn Skill"),
    Longitude("Longitude"),
    MacAddress("MAC Address"),
    Md5("MD5"),
    MedicareBeneficiaryId("Medicare Beneficiary ID"),
    MimeType("MIME Type"),
    MobileDeviceBrand("Mobile Device Brand"),
    MobileDeviceModel("Mobile Device Model"),
    MobileDeviceOs("Mobile Device OS"),
    MobileDeviceReleaseDate("Mobile Device Release Date"),
    Money("Money"),
    MongodbObjectid("MongoDB ObjectID"),
    MovieGenres("Movie Genres"),
    MovieTitle("Movie Title"),
    NatoPhonetic("Nato Phonetic"),
    NaughtyString("Naughty String"),
    NhsNumber("NHS Number"),
    NormalDistribution("Normal Distribution"),
    Number("Number"),
    Paragraphs("Paragraphs"),
    Password("Password"),
    PasswordHash("Password Hash"),
    Phone("Phone"),
    PlantCommonName("Plant Common Name"),
    PlantFamily("Plant Family"),
    PlantScientificName("Plant Scientific Name"),
    PoissonDistribution("Poisson Distribution"),
    PostalCode("Postal Code"),
    ProductGrocery("Product (Grocery)"),
    Race("Race"),
    RegularExpression("Regular Expression"),
    RepeatingElement("Repeating Element"),
    RowNumber("Row Number"),
    Scenario("Scenario"),
    Sentences("Sentences"),
    Sequence("Sequence"),
    Sha1("SHA1"),
    Sha256("SHA256"),
    ShirtSize("Shirt Size"),
    ShortHexColor("Short Hex Color"),
    Slogan("Slogan"),
    SqlExpression("SQL Expression"),
    Ssn("SSN"),
    State("State"),
    StateAbbrev("State (abbrev)"),
    StockIndustry("Stock Industry"),
    StockMarket("Stock Market"),
    StockMarketCap("Stock Market Cap"),
    StockName("Stock Name"),
    StockSector("Stock Sector"),
    StockSymbol("Stock Symbol"),
    StreetAddress("Street Address"),
    StreetName("Street Name"),
    StreetNumber("Street Number"),
    StreetSuffix("Street Suffix"),
    Suffix("Suffix"),
    Template("Template"),
    TezosAccount("Tezos Account"),
    TezosBlock("Tezos Block"),
    TezosContract("Tezos Contract"),
    TezosOperation("Tezos Operation"),
    TezosSignature("Tezos Signature"),
    Time("Time"),
    TimeZone("Time Zone"),
    Title("Title"),
    TopLevelDomain("Top Level Domain"),
    Ulid("ULID"),
    University("University"),
    Url("URL"),
    UserAgent("User Agent"),
    Username("Username"),
    Words("Words");

    private final String name;

    private DataTypes(String s){
        name = s;
    }

    private boolean equalsName(String otherName){
        return name.equals(otherName);
    }

    public String toString(){
        return this.name;
    }



}
